\\EUDVMMSSQL101\D$\DATA\SQL_Support\SS0\SQL_Installation\SQL2017\SQL2017_STD
\\EUDVMMSSQL101\D$\DATA\SQL_Support\SS0\SQL_Installation\SQL2016\SQL2016_STD
\\EUDVMMSSQL101\D$\DATA\SQL_Support\SS0\SQL_Installation\SQL2016\SQL2014_STD
\\EUDVMMSSQL101\D$\DATA\SQL_Support\SS0\SQL_Installation\SQL2016\SQL2012_STD

====================================================================================
## SQL Uninstallation direct script
$instance = Read-Host "Enter Instance name to delete"
$instance = $instance.ToUpper()
C:\temp\SQL2014\STD\setup.exe 
/Q 
/ACTION=Uninstall 
/IACCEPTSQLSERVERLICENSETERMS
/HELP="False"
/INDICATEPROGRESS="false"
/X86="False"
/FEATURES="SQLENGINE,REPLICATION,FULLTEXT"
/INDICATEPROGRESS="False"
/INSTANCENAME="$instance" 

====================================================================================

\\Eudvmmssql101\d$\DATA\SQL_Support\SS0\SQL_Installation\SQL2017\SQL2017_STD\setup.exe
/ACTION="Install"
/Q="false"
/IACCEPTSQLSERVERLICENSETERMS
/UpdateEnabled="true"
/ERRORREPORTING="False"
/SUPPRESSPRIVACYSTATEMENTNOTICE="False"
/PID="B9GQY-GBG4J-282NY-QRG4X-KQBCR"
/USEMICROSOFTUPDATE="False"
/FEATURES="SQLENGINE,REPLICATION,FULLTEXT,DQC,CONN,BC,SDK,BOL,SNAC_SDK"
/UpdateSource="C:\temp\SQL2016_STD"
/HELP="False"
/INDICATEPROGRESS="false"
/X86="False"
/INSTANCENAME="SQL102"
/SQMREPORTING="False"
/INSTANCEID="SQL102"
/INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"
/INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"
/INSTANCEDIR="C:\Program Files\Microsoft SQL Server"
/FILESTREAMLEVEL="0"
/ENABLERANU="False"
/SQLSYSADMINACCOUNTS="KONENET\ROL-Generic-TSMY_DB"
/INSTALLSQLDATADIR="D:\DATA\SQL\SY0"
/SQLUSERDBDIR="D:\DATA\SQL\SD0"
/SQLUSERDBLOGDIR="D:\DATA\SQL\SL0"
/SQLTEMPDBDIR="D:\DATA\SQL\ST0"
/SQLTEMPDBLOGDIR="D:\DATA\SQL\ST0"
/SQLBACKUPDIR="D:\DATA\SQL_Support\SS0"
/SQLSVCACCOUNT="NT Service\MSSQL$SQL102"
/SQLSVCSTARTUPTYPE="Automatic"
/SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS"
/AGTSVCACCOUNT="NT Service\SQLAgent$SQL102"
/AGTSVCSTARTUPTYPE="Manual"
/COMMFABRICPORT="0"
/ADDCURRENTUSERASSQLADMIN="False"
/SQLSVCINSTANTFILEINIT="False"
/TCPENABLED="1"
/BROWSERSVCSTARTUPTYPE="Automatic"
/FTSVCACCOUNT="NT Service\MSSQLFDLauncher$SQL102"
/SECURITYMODE="SQL"
/SAPWD="Password#123"
/SQLSYSADMINACCOUNTS="KONENET\ROL-Generic-TSMY_DB"
/SQLTEMPDBFILECOUNT="4"
/SQLTEMPDBFILESIZE="8"
/SQLTEMPDBFILEGROWTH="64"
/SQLTEMPDBLOGFILESIZE="8"
/SQLTEMPDBLOGFILEGROWTH="64"
/FTSVCACCOUNT="NT Service\MSSQLFDLauncher$SQL102"
